declare class CharInfoEx {
    constructor();
    private static bytesToUuidV4;
    private static uuidV4ToBytes;
    private static writeStringUTF16Fixed;
    static FromSaveFileArrayBuffer(saveBuffer: ArrayBufferLike): CharInfoEx[];
    static FromSaveFileArrayBuffer(saveBuffer: ArrayBufferLike, index: number): CharInfoEx;
    static FromSaveFileArrayBuffer(saveBuffer: ArrayBufferLike, indexes: number[]): CharInfoEx[];
    static FromArrayLike(arrayLike: Iterable<number>): CharInfoEx;
    static FromArrayBuffer(buffer: ArrayBufferLike): CharInfoEx;
    ToArrayBuffer(): ArrayBuffer;
    static ToArrayBuffer(charInfo: CharInfoEx): ArrayBuffer;
    toJson(pretty?: boolean): string;
    static fromJson(jsonString: string): CharInfoEx;
    static fromJson(jsonString: string): CharInfoEx[];
    uuidv4: string;
    name: string;
    fontRegion: number;
    gender: number;
    height: number;
    build: number;
    regionMove: number;
    faceFlags: number;
    facelineType: number;
    facelineColor: number;
    wrinkleLowerType: number;
    wrinkleLowerScale: number;
    wrinkleLowerAspect: number;
    wrinkleLowerX: number;
    wrinkleLowerY: number;
    wrinkleUpperType: number;
    wrinkleUpperScale: number;
    wrinkleUpperAspect: number;
    wrinkleUpperX: number;
    wrinkleUpperY: number;
    makeup0: number;
    makeup0Color: number;
    makeup0Scale: number;
    makeup0Aspect: number;
    makeup0X: number;
    makeup0Y: number;
    makeup1: number;
    makeup1Color: number;
    makeup1Scale: number;
    makeup1Aspect: number;
    makeup1X: number;
    makeup1Y: number;
    hairType: number;
    hairColor0: number;
    hairColor1: number;
    hairTypeFront: number;
    hairTypeBack: number;
    hairStyle: number;
    earType: number;
    earScale: number;
    earY: number;
    eyeType: number;
    eyeColor: number;
    eyeScale: number;
    eyeAspect: number;
    eyeRotate: number;
    eyeX: number;
    eyeY: number;
    eyeShadowColor: number;
    eyeHighlightType: number;
    eyeHighlightScale: number;
    eyeHighlightAspect: number;
    eyeHighlightRotate: number;
    eyeHighlightX: number;
    eyeHighlightY: number;
    eyelashUpperType: number;
    eyelashUpperScale: number;
    eyelashUpperAspect: number;
    eyelashUpperRotate: number;
    eyelashUpperX: number;
    eyelashUpperY: number;
    eyelashLowerType: number;
    eyelashLowerScale: number;
    eyelashLowerAspect: number;
    eyelashLowerRotate: number;
    eyelashLowerX: number;
    eyelashLowerY: number;
    eyelidUpperType: number;
    eyelidUpperScale: number;
    eyelidUpperAspect: number;
    eyelidUpperRotate: number;
    eyelidUpperX: number;
    eyelidUpperY: number;
    eyelidLowerType: number;
    eyelidLowerScale: number;
    eyelidLowerAspect: number;
    eyelidLowerRotate: number;
    eyelidLowerX: number;
    eyelidLowerY: number;
    eyebrowType: number;
    eyebrowColor: number;
    eyebrowScale: number;
    eyebrowAspect: number;
    eyebrowRotate: number;
    eyebrowX: number;
    eyebrowY: number;
    noseType: number;
    noseScale: number;
    noseY: number;
    mouthType: number;
    mouthColor: number;
    mouthScale: number;
    mouthAspect: number;
    mouthRotate: number;
    mouthY: number;
    beardType: number;
    beardColor: number;
    beardShortType: number;
    beardShortColor: number;
    mustacheType: number;
    mustacheColor: number;
    mustacheScale: number;
    mustacheAspect: number;
    mustacheY: number;
    glassType1: number;
    glassColor1: number;
    glassScale: number;
    glassAspect: number;
    glassY: number;
    glassType2: number;
    glassColor2: number;
    moleScale: number;
    moleX: number;
    moleY: number;
    unkDefault45: number;
}

export { CharInfoEx };
