"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CharInfoOffset = void 0;
var CharInfoOffset;
(function (CharInfoOffset) {
    CharInfoOffset[CharInfoOffset["createId1"] = 0] = "createId1";
    CharInfoOffset[CharInfoOffset["createId2"] = 4] = "createId2";
    CharInfoOffset[CharInfoOffset["createId3"] = 8] = "createId3";
    CharInfoOffset[CharInfoOffset["createId4"] = 12] = "createId4";
    CharInfoOffset[CharInfoOffset["name"] = 16] = "name";
    CharInfoOffset[CharInfoOffset["fontRegion"] = 38] = "fontRegion";
    CharInfoOffset[CharInfoOffset["gender"] = 39] = "gender";
    CharInfoOffset[CharInfoOffset["height"] = 40] = "height";
    CharInfoOffset[CharInfoOffset["build"] = 41] = "build";
    CharInfoOffset[CharInfoOffset["regionMove"] = 42] = "regionMove";
    // Bit 0 - Unknown
    // Bit 1 - Bangs Side
    // Bit 2 - Back Dual Color
    // Bit 3 - Bangs Dual Color
    // Bit 4 - Eye Shadow Enabled
    // Bit 5 - Mouth Invert?
    // Bit 6 - Moustache Inverted
    // Bit 7 - Mole
    CharInfoOffset[CharInfoOffset["faceFlags"] = 43] = "faceFlags";
    CharInfoOffset[CharInfoOffset["facelineType"] = 44] = "facelineType";
    CharInfoOffset[CharInfoOffset["facelineColor"] = 45] = "facelineColor";
    CharInfoOffset[CharInfoOffset["wrinkleLower"] = 46] = "wrinkleLower";
    CharInfoOffset[CharInfoOffset["wrinkleLowerScale"] = 47] = "wrinkleLowerScale";
    CharInfoOffset[CharInfoOffset["wrinkleLowerAspect"] = 48] = "wrinkleLowerAspect";
    CharInfoOffset[CharInfoOffset["wrinkleLowerX"] = 49] = "wrinkleLowerX";
    CharInfoOffset[CharInfoOffset["wrinkleLowerY"] = 50] = "wrinkleLowerY";
    CharInfoOffset[CharInfoOffset["wrinkleUpper"] = 51] = "wrinkleUpper";
    CharInfoOffset[CharInfoOffset["wrinkleUpperScale"] = 52] = "wrinkleUpperScale";
    CharInfoOffset[CharInfoOffset["wrinkleUpperAspect"] = 53] = "wrinkleUpperAspect";
    CharInfoOffset[CharInfoOffset["wrinkleUpperX"] = 54] = "wrinkleUpperX";
    CharInfoOffset[CharInfoOffset["wrinkleUpperY"] = 55] = "wrinkleUpperY";
    CharInfoOffset[CharInfoOffset["makeup0"] = 56] = "makeup0";
    CharInfoOffset[CharInfoOffset["makeup0Color"] = 57] = "makeup0Color";
    CharInfoOffset[CharInfoOffset["makeup0Scale"] = 58] = "makeup0Scale";
    CharInfoOffset[CharInfoOffset["makeup0Aspect"] = 59] = "makeup0Aspect";
    CharInfoOffset[CharInfoOffset["makeup0X"] = 60] = "makeup0X";
    CharInfoOffset[CharInfoOffset["makeup0Y"] = 61] = "makeup0Y";
    CharInfoOffset[CharInfoOffset["makeup1"] = 62] = "makeup1";
    CharInfoOffset[CharInfoOffset["makeup1Color"] = 63] = "makeup1Color";
    CharInfoOffset[CharInfoOffset["makeup1Scale"] = 64] = "makeup1Scale";
    CharInfoOffset[CharInfoOffset["makeup1Aspect"] = 65] = "makeup1Aspect";
    CharInfoOffset[CharInfoOffset["makeup1X"] = 66] = "makeup1X";
    CharInfoOffset[CharInfoOffset["makeup1Y"] = 67] = "makeup1Y";
    CharInfoOffset[CharInfoOffset["hairType"] = 68] = "hairType";
    CharInfoOffset[CharInfoOffset["hairColor0"] = 70] = "hairColor0";
    CharInfoOffset[CharInfoOffset["hairColor1"] = 71] = "hairColor1";
    CharInfoOffset[CharInfoOffset["hairTypeFront"] = 72] = "hairTypeFront";
    CharInfoOffset[CharInfoOffset["hairTypeBack"] = 73] = "hairTypeBack";
    // Bit 0 - Left Side
    // Bit 1 - Right Side
    CharInfoOffset[CharInfoOffset["hairStyle"] = 74] = "hairStyle";
    CharInfoOffset[CharInfoOffset["earType"] = 75] = "earType";
    CharInfoOffset[CharInfoOffset["earScale"] = 76] = "earScale";
    CharInfoOffset[CharInfoOffset["earY"] = 77] = "earY";
    CharInfoOffset[CharInfoOffset["eyeType"] = 78] = "eyeType";
    CharInfoOffset[CharInfoOffset["eyeColor"] = 79] = "eyeColor";
    CharInfoOffset[CharInfoOffset["eyeScale"] = 80] = "eyeScale";
    CharInfoOffset[CharInfoOffset["eyeAspect"] = 81] = "eyeAspect";
    CharInfoOffset[CharInfoOffset["eyeRotate"] = 82] = "eyeRotate";
    CharInfoOffset[CharInfoOffset["eyeX"] = 83] = "eyeX";
    CharInfoOffset[CharInfoOffset["eyeY"] = 84] = "eyeY";
    CharInfoOffset[CharInfoOffset["eyeShadowColor"] = 85] = "eyeShadowColor";
    CharInfoOffset[CharInfoOffset["eyeHighlightType"] = 86] = "eyeHighlightType";
    CharInfoOffset[CharInfoOffset["eyeHighlightScale"] = 87] = "eyeHighlightScale";
    CharInfoOffset[CharInfoOffset["eyeHighlightAspect"] = 88] = "eyeHighlightAspect";
    CharInfoOffset[CharInfoOffset["eyeHighlightRotate"] = 89] = "eyeHighlightRotate";
    CharInfoOffset[CharInfoOffset["eyeHighlightX"] = 90] = "eyeHighlightX";
    CharInfoOffset[CharInfoOffset["eyeHighlightY"] = 91] = "eyeHighlightY";
    CharInfoOffset[CharInfoOffset["eyelashUpperType"] = 92] = "eyelashUpperType";
    CharInfoOffset[CharInfoOffset["eyelashUpperScale"] = 93] = "eyelashUpperScale";
    CharInfoOffset[CharInfoOffset["eyelashUpperAspect"] = 94] = "eyelashUpperAspect";
    CharInfoOffset[CharInfoOffset["eyelashUpperRotate"] = 95] = "eyelashUpperRotate";
    CharInfoOffset[CharInfoOffset["eyelashUpperX"] = 96] = "eyelashUpperX";
    CharInfoOffset[CharInfoOffset["eyelashUpperY"] = 97] = "eyelashUpperY";
    CharInfoOffset[CharInfoOffset["eyelashLowerType"] = 98] = "eyelashLowerType";
    CharInfoOffset[CharInfoOffset["eyelashLowerScale"] = 99] = "eyelashLowerScale";
    CharInfoOffset[CharInfoOffset["eyelashLowerAspect"] = 100] = "eyelashLowerAspect";
    CharInfoOffset[CharInfoOffset["eyelashLowerRotate"] = 101] = "eyelashLowerRotate";
    CharInfoOffset[CharInfoOffset["eyelashLowerX"] = 102] = "eyelashLowerX";
    CharInfoOffset[CharInfoOffset["eyelashLowerY"] = 103] = "eyelashLowerY";
    CharInfoOffset[CharInfoOffset["eyeLidUpperType"] = 104] = "eyeLidUpperType";
    CharInfoOffset[CharInfoOffset["eyeLidUpperScale"] = 105] = "eyeLidUpperScale";
    CharInfoOffset[CharInfoOffset["eyeLidUpperAspect"] = 106] = "eyeLidUpperAspect";
    CharInfoOffset[CharInfoOffset["eyeLidUpperRotate"] = 107] = "eyeLidUpperRotate";
    CharInfoOffset[CharInfoOffset["eyeLidUpperX"] = 108] = "eyeLidUpperX";
    CharInfoOffset[CharInfoOffset["eyeLidUpperY"] = 109] = "eyeLidUpperY";
    CharInfoOffset[CharInfoOffset["eyelidLowerType"] = 110] = "eyelidLowerType";
    CharInfoOffset[CharInfoOffset["eyelidLowerScale"] = 111] = "eyelidLowerScale";
    CharInfoOffset[CharInfoOffset["eyelidLowerAspect"] = 112] = "eyelidLowerAspect";
    CharInfoOffset[CharInfoOffset["eyelidLowerRotate"] = 113] = "eyelidLowerRotate";
    CharInfoOffset[CharInfoOffset["eyelidLowerX"] = 114] = "eyelidLowerX";
    CharInfoOffset[CharInfoOffset["eyelidLowerY"] = 115] = "eyelidLowerY";
    CharInfoOffset[CharInfoOffset["eyebrowType"] = 116] = "eyebrowType";
    CharInfoOffset[CharInfoOffset["eyebrowColor"] = 117] = "eyebrowColor";
    CharInfoOffset[CharInfoOffset["eyebrowScale"] = 118] = "eyebrowScale";
    CharInfoOffset[CharInfoOffset["eyebrowAspect"] = 119] = "eyebrowAspect";
    CharInfoOffset[CharInfoOffset["eyebrowRotate"] = 120] = "eyebrowRotate";
    CharInfoOffset[CharInfoOffset["eyebrowX"] = 121] = "eyebrowX";
    CharInfoOffset[CharInfoOffset["eyebrowY"] = 122] = "eyebrowY";
    CharInfoOffset[CharInfoOffset["noseType"] = 123] = "noseType";
    CharInfoOffset[CharInfoOffset["noseScale"] = 124] = "noseScale";
    CharInfoOffset[CharInfoOffset["noseY"] = 125] = "noseY";
    CharInfoOffset[CharInfoOffset["mouthType"] = 126] = "mouthType";
    CharInfoOffset[CharInfoOffset["mouthColor"] = 127] = "mouthColor";
    CharInfoOffset[CharInfoOffset["mouthScale"] = 128] = "mouthScale";
    CharInfoOffset[CharInfoOffset["mouthAspect"] = 129] = "mouthAspect";
    CharInfoOffset[CharInfoOffset["mouthRotate"] = 130] = "mouthRotate";
    CharInfoOffset[CharInfoOffset["mouthY"] = 131] = "mouthY";
    CharInfoOffset[CharInfoOffset["beardType"] = 132] = "beardType";
    CharInfoOffset[CharInfoOffset["beardColor"] = 133] = "beardColor";
    CharInfoOffset[CharInfoOffset["beardShortType"] = 134] = "beardShortType";
    CharInfoOffset[CharInfoOffset["beardShortColor"] = 135] = "beardShortColor";
    CharInfoOffset[CharInfoOffset["mustacheType"] = 136] = "mustacheType";
    CharInfoOffset[CharInfoOffset["mustacheColor"] = 137] = "mustacheColor";
    CharInfoOffset[CharInfoOffset["mustacheScale"] = 138] = "mustacheScale";
    CharInfoOffset[CharInfoOffset["mustacheAspect"] = 139] = "mustacheAspect";
    CharInfoOffset[CharInfoOffset["mustacheY"] = 140] = "mustacheY";
    CharInfoOffset[CharInfoOffset["glassType1"] = 141] = "glassType1";
    CharInfoOffset[CharInfoOffset["glassColor1"] = 142] = "glassColor1";
    CharInfoOffset[CharInfoOffset["glassScale"] = 143] = "glassScale";
    CharInfoOffset[CharInfoOffset["glassAspect"] = 144] = "glassAspect";
    CharInfoOffset[CharInfoOffset["glassY"] = 145] = "glassY";
    CharInfoOffset[CharInfoOffset["glassType2"] = 146] = "glassType2";
    CharInfoOffset[CharInfoOffset["glassColor2"] = 147] = "glassColor2";
    CharInfoOffset[CharInfoOffset["moleScale"] = 148] = "moleScale";
    CharInfoOffset[CharInfoOffset["moleX"] = 149] = "moleX";
    CharInfoOffset[CharInfoOffset["moleY"] = 150] = "moleY";
    CharInfoOffset[CharInfoOffset["unkDefault45"] = 151] = "unkDefault45";
})(CharInfoOffset || (exports.CharInfoOffset = CharInfoOffset = {}));
